services:
  lancache:
    image: lancachenet/monolithic:latest
    ports:
    - ${LANCACHE_IP}:80:80
    restart: unless-stopped
    volumes:
    - ./cache/data:/data/cache
    - ./cache/logs:/data/logs
  lanparty-dns:
    environment:
    - DNS_FORWARDER="${DNS_FORWARDER}"
    - WILDCARD_DNS=minecraft.lan=${GAMES_IP}, steam.lan=${GAMES_IP}, ts.lan=${SERVICES_IP},
      party.lan=${SERVICES_IP}
    image: cytopia/bind:latest
    ports:
    - ${SERVICES_IP}:53:53/udp
    restart: unless-stopped
  minecraft-server:
    image: refractix/mc-server:latest
    ports:
    - ${GAMES_IP}:25565:25565
    restart: unless-stopped
    volumes:
    - ${MINECRAFT_ETC_VOLUME}:/opt/minecraft/etc
  party-web:
    image: nginx
    ports:
    - ${PARTY_IP}:80:80
    restart: unless-stopped
  sniproxy:
    image: lancachenet/sniproxy:latest
    ports:
    - 443:443
    restart: unless-stopped
  steamcache-dns:
    environment:
    - UPSTREAM_DNS=${SERVICES_DNS}
    - USE_GENERIC_CACHE=true
    - LANCACHE_IP="${LANCACHE_IP}"
    image: lancachenet/lancache-dns:latest
    ports:
    - ${LANCACHE_IP}:53:53/udp
    restart: unless-stopped
  teamspeak-maria:
    environment:
    - MYSQL_ROOT_PASSWORD="${TEAMSPEAK_DB_PASSWORD}"
    - MYSQL_DATABASE=teamspeak
    image: mariadb
    restart: unless-stopped
  teamspeak-server:
    environment:
    - TS3SERVER_DB_PLUGIN=ts3db_mariadb
    - TS3SERVER_DB_SQLCREATEPATH=create_mariadb
    - TS3SERVER_DB_HOST=teamspeak-maria
    - TS3SERVER_DB_USER=root
    - TS3SERVER_DB_PASSWORD="${TEAMSPEAK_DB_PASSWORD}"
    - TS3SERVER_DB_NAME=teamspeak
    - TS3SERVER_DB_WAITUNTILREADY=30
    - TS3SERVER_LICENSE=accept
    image: teamspeak
    ports:
    - ${SERVIES_IP}:9987:9987/udp
    - ${SERVIES_IP}:10011:10011
    - ${SERVIES_IP}:30033:30033
    restart: unless-stopped
  ttt-server:
    environment:
    - WORKSHOP_COLLECTION_ID="${TTT_WORKSHOP_COLLECTION_ID}"
    - AUTH_KEY="${TTT_AUTH_KEY}"
    image: refractix/ttt:latest
    ports:
    - ${GAMES_IP}:27015:27015/udp
    - ${GAMES_IP}:27015:27015/tcp
    restart: unless-stopped
    volumes:
    - ./data/ttt/data/:/home/steam/data/
version: '3'
