version: "3"

services:

# test AAAAAA

# standard stuff

  lanparty-dns:
    restart: unless-stopped
    image: cytopia/bind:latest
    environment:
      - DNS_FORWARDER="${DNS_FORWARDER}"
      - WILDCARD_DNS=minecraft.lan=${GAMES_IP}, steam.lan=${GAMES_IP}, ts.lan=${SERVICES_IP}, party.lan=${SERVICES_IP}
    ports:
      - "${SERVICES_IP}:53:53/udp"

# Party support

  party-web:
    restart: unless-stopped
    image: nginx
    ports:
      - ${SERVICES_IP}:80:80


  